### ISSUE TITLE
/getgroup command

### ISSUE THREAD

**Issue by thecrankytech** [mozi-h/Better-Doors#3]
Not to be a pain the ass but, after creating a door group and assigning a few doors to it, I tried the /getgroup command to see if it'd grab the doors group or tell me it isn't in a group. It doesn't seem to work or bring anything up in the chat nor in the server/client console.

**Comment by mozi-h** [comment]
Could not reproduce – on my testing server, everything works as intended (`/getgroup` makes a hint pop up and as such also logs to client console).
As it seems like `/setgroup` works for you, the add-on must be installed. My best guess is that it's somehow corrupted or overwritten by other spaghetti. Do all commands show up in the F1 menu? Otherwise, try re-installing it.

Also, reporting bugs isn't a pain in the ass – but helpful 👍
